// <auto-generated />
using College.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace College.Migrations
{
    [DbContext(typeof(ExamDbContext))]
    partial class ExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("College.Models.CandidateExam", b =>
                {
                    b.Property<string>("CRollNo")
                        .HasColumnType("text");

                    b.Property<string>("CName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CRollNo");

                    b.ToTable("CandidateExams");
                });

            modelBuilder.Entity("College.Models.Marks", b =>
                {
                    b.Property<int>("MarksId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MarksId"));

                    b.Property<string>("CRollNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MarksObtained")
                        .HasColumnType("numeric");

                    b.Property<string>("SubCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MarksId");

                    b.HasIndex("CRollNo");

                    b.HasIndex("SubCode");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("College.Models.Subject", b =>
                {
                    b.Property<string>("SubCode")
                        .HasColumnType("text");

                    b.Property<int>("FullMarks")
                        .HasColumnType("integer");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SubCode");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("College.Models.Marks", b =>
                {
                    b.HasOne("College.Models.CandidateExam", "CandidateExam")
                        .WithMany("Marks")
                        .HasForeignKey("CRollNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("College.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CandidateExam");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("College.Models.CandidateExam", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
